---
# handlers file for ansible-role-deployment-automation
- name: Update Helm repository cache for metallb
  listen: update metallb helm repository cache
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb
    state: present
    force_update: true

- name: Update Helm repository cache for zabbix-community
  listen: update zabbix-community helm repository cache
  kubernetes.core.helm_repository:
    name: zabbix-community
    repo_url: https://zabbix-community.github.io/helm-zabbix
    state: present
    force_update: true